package common;

public enum Action {
    INPUT_PRINTABLE_CHAR,
    BACKSPACE_DELETE,
    DEL_DELETE,
    MOVE_CURSOR_RIGHT,
    MOVE_CURSOR_LEFT,
    MOVE_CURSOR_UP,
    MOVE_CURSOR_DOWN,
    MOVE_CURSOR,
    ENTER_NEW_ROW,
    INPUT_TAB,
    UNDO,
    DO,
    QUIT,

    NONE
}
